### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by DrDaveone** [belibak/add-free-announcers#1]
добавил модуль Requests. создал папку, закинул один торрент. запустил run, выкидывает с ошибкой 
` Traceback (most recent call last):
** IDLE Internal Exception: 
  File "C:\Program Files\Python36\lib\idlelib\run.py", line 460, in runcode
    exec(code, self.locals)
  File "C:\Users\DEFAULT.DPC\Desktop\add-free-announcers-master\run.py", line 60, in <module>
    add_announcers(i)
  File "C:\Users\DEFAULT.DPC\Desktop\add-free-announcers-master\run.py", line 39, in add_announcers
    ann_list = dct['announce-list']
KeyError: 'announce-list' `
папку announcers_added создает, внутри ничего

**Comment by belibak** [comment]
Можно как-то этот торрент файл заполучить?

UPD Насколько я понял, в Вашем файле нет анносеров. Поправил код.

**Comment by DrDaveone** [comment]
держите
[Эй, Арнольд!.zip](https://github.com/belibak/add-free-announcers/files/981313/default.zip)
